### ISSUE TITLE
Add ability to warn user if incorrect/incomplete data was entered before committing records to store

### ISSUE THREAD

**Issue by AlexRyanUSACE** [HydrologicEngineeringCenter/nsi-survey-tool#11]
Right now if you enter values that do not pass validator checks, it simply will not dispatch and will leave the fields to their default values, but won't notify the user.  I tried looking into a way to show a message box or something to alert the user when this happens, but no luck so far.  Maybe just like an always visible quasi-console textbox at the bottom?

**Comment by HenryGeorgist** [comment]
we can do a lot of things. but in general - we are wanting to not commit to database and then let the user know something was wrong.
mabye we can have a selector on validity for each entry that governs the color of the background of the textbox? if true no background color or white? if false, red background!?

**Comment by HenryGeorgist** [comment]
i added a style to color the border red.
