### ISSUE TITLE
Add new page to allow users to select create new survey, open existing survey, or manage surveys

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-survey-tool#29]

**Comment by HenryGeorgist** [comment]
![image](https://user-images.githubusercontent.com/7872881/130169441-a52d7261-11c1-44f3-8331-b2cda28ffd99.png)

**Comment by HenryGeorgist** [comment]
the image above is a general idea, the icons could be different, and we of course want the banner and css to be consistent with the current nsi-survey-tool css/banner
no search necessary so eschew the central FEMA/USACE Model Library label and search models text box

**Comment by trietmnj** [comment]
How's this? It's currently mapped to /nsi-survey/splash. Each button should grow a bit on hover. Should be in branch tmnt. I haven't mapped any functionality to the buttons, they're just for display right now.

![image](https://user-images.githubusercontent.com/53122983/130386568-dc318691-7a5e-4985-a6d1-2264fc85296c.png)

**Comment by HenryGeorgist** [comment]
Good start.

**Comment by HenryGeorgist** [comment]
can we drop the background image and remove the text "Survey" and "Tools"

Can we make the background either white or black (to match the login page) ?

Can we remove the blurr effect on the brown background?

Can we make the brown background either black or white (opposite of the main background)

Make the text of the graphics and text all the same as the main background color

Make the tool names "Create New Survey" "Modify Existing Survey" and "Manage All Surveys"  

I think the icon for the manage all should be a gear.

**Comment by trietmnj** [comment]
Like this?

![image](https://user-images.githubusercontent.com/53122983/130712047-fc76d5a2-9160-40f4-b532-c5d437a3fee2.png)

**Comment by HenryGeorgist** [comment]
what do you think?  I am not sure we are quite there yet, that one makes me squint... haha

**Comment by HenryGeorgist** [comment]
i like the black bg-dark from darkly, and the https://bootswatch.com/darkly/   i think it goes well with the bg-light from the third navibar down.

I dont know the hexidecimal on those, but maybe try those instead of the pure black and pure white

**Comment by trietmnj** [comment]
Ok, how does it look?

![image](https://user-images.githubusercontent.com/53122983/130713514-0830f984-e6fb-4385-8b7b-090bfdd3d435.png)

**Comment by HenryGeorgist** [comment]
that is alot more pleasant  - what do you think?

**Comment by HenryGeorgist** [comment]
The black banner seems a bit much now, but in general i like that color scheme

**Comment by HenryGeorgist** [comment]
i like cyborg too https://bootswatch.com/cyborg/

**Comment by trietmnj** [comment]
It's perfect without the banner

**Comment by trietmnj** [comment]
black is too much

**Comment by trietmnj** [comment]
well actually it looks better on the actual html page compared to the picture, I think

**Comment by HenryGeorgist** [comment]
yeah. switch the banner to match the darkly scheme

**Comment by trietmnj** [comment]
so the NavBar is currently a reusable component, changing it would change the bar on every single page. I can make duplicate into a more customized version just for the splash page too.

**Comment by HenryGeorgist** [comment]
i think we should update the whole page to the new styling

**Comment by trietmnj** [comment]
Perfect!

**Comment by trietmnj** [comment]
![image](https://user-images.githubusercontent.com/53122983/130716904-29bb5912-a80a-4989-8d35-ad6de57a5c53.png)

**Comment by HenryGeorgist** [comment]
That works for me. we might play around with it more as we keep adding information, but this is a great start.
