### ISSUE TITLE
create new survey page

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-survey-tool#30]
develop a page to create a new survey. 

A survey must:
1.	Have a name
2.	Have an uploaded dataset of survey point locations
3.	have a list of 0-many surveyors
4.	have a list of 1-many survey owners
5.	be active or inactive
Any logged in user can create a new survey.
The creator will be assigned as an owner and a surveyor for the created survey
The survey owners can add surveyors, remove surveyors, mark a survey as inactive, and generate a survey report.

**Comment by HenryGeorgist** [comment]
![image](https://user-images.githubusercontent.com/7872881/130676147-37e22c6d-df08-4b38-930a-68b559b42ccc.png)

**Comment by HenryGeorgist** [comment]
Do we want to do modal dialogue instead of page navigation? I was kinda thinking navigation because it would be the same page for managing a selected survey

**Comment by HenryGeorgist** [comment]
Modal could work i guess. Just not what i was thinking

**Comment by trietmnj** [comment]
I thinking modal unless the functionality is already built, because it would be a lot more responsive, less overhead reloading and finicking with the rerouting.

**Comment by HenryGeorgist** [comment]
Functionality is not yet built, lets go with modal if that is your preference right now. We might be changing that down the road as we get a functional application and play with it some

**Comment by HenryGeorgist** [comment]
The add survey points should allow a user to browse to a file on their computer.

**Comment by trietmnj** [comment]
Alright

**Comment by HenryGeorgist** [comment]
based on the demo on 11/24/2021 this work is complete
