### ISSUE TITLE
Allow user to manage an existing survey

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-survey-tool#33]
### Background
A user can create surveys in the nsi-survey-tool. These surveys are intended to support a specific project objective. 

### User Story
As a survey owner, I want to manage a survey during the life of a survey so that I can get results, add or remove surveyors, and set the survey to inactive.

### Purpose
When a survey is created the owner can add surveyors, it is likely that over the lifespan of a survey, new surveyors may need to be added or existing surveyors may need to be removed. 
Also a survey owner needs to be able to access the survey results as raw data minimally, ideally, future features will allow for reporting on survey results.
A survey owner needs to be able to set a survey to inactive.

### WorkFlow

- Survey owner logs into nsi-survey-tool
- Survey owner is presented with options to create a new survey, manage existing surveys, or participate in existing survey
- Survey owner selects manage existing surveys (including inactive surveys they are owners of)
- Survey owner selects a survey
- survey owner can add/remove surveyors, download data, or set survey to inactive or active.
- survey owner can navigate back to main page.

**Comment by trietmnj** [comment]
@HenryGeorgist @GitLutz 

> survey owner can add/remove surveyors, download data, or set survey to inactive or active.

What does "download data" mean? Are we talking about conducted survey data, existing structure data already in the NSI, or survey metadata? Let's concretely define a use-case to determine how what and how data could be presented here.

**Comment by HenryGeorgist** [comment]
what is survey metadata?
The objective is to download the results of the survey, so i think that is conducted survey data. Randy had an export to csv endpoint on the nsi-survey-server

**Comment by trietmnj** [comment]
Metadata would be like when the survey was created, what structures are in the survey, which has already been surveyed, when was each structure logged, who entered data for which structure, etc.

**Comment by trietmnj** [comment]
Ok, I see that endpoint
> /survey/:surveyid/report

**Comment by trietmnj** [comment]
This issue is closable
