### ISSUE TITLE
Allow user to Access an existing survey

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/nsi-survey-tool#34]
### Background
The nsi-survey-tool provides a user the ability to create and/or participate in a survey of structures. A survey collects information about structures regarding visible attributes that are useful in defining structure characteristics for natural hazards consequence assessments.

### User Story
As a surveyor, I want to participate in a survey for a local project so that I can collect a sample of the attributes used in a consequence assessment.

### Purpose
The sample of attributes can be useful for defining assumptions to update the base level NSI data or a local inventory. Additionally, the sample data can be used to define uncertainty distributions if a full sample is not feasible for a project.

### WorkFlow
- Login to NSI survey tool
- User is presented with Active Surveys they are registered for.
- User selects "access existing surveys" 
- a list of surveys the logged in user is a member of is presented
- The user selects a survey to participate in
- User routed to map with survey-tray plugin loaded and ready to present next survey element for selected survey
- User requests next survey element
- User fills out survey
- user submits survey record to selected active survey.

**Comment by trietmnj** [comment]
This issue is closable
