### ISSUE TITLE
Unfinished survey creation

### ISSUE THREAD

**Issue by trietmnj** [HydrologicEngineeringCenter/nsi-survey-tool#44]
Currently, if the survey was created with a name and description, it will automatically be "active" but there would be no elements. Active surveys without any elements can be used to access the map page and the survey tray, but it triggers an unresolved bug in the survey assignment algorithm. Should we reconsider what it means for a survey to be active?

In the manage-all prompt, there is now a feature to view the elements but nothing yet to modify, so the only opportunity to add in elements would be at the survey creation.

**Comment by HenryGeorgist** [comment]
i think adding elements might be an important workflow - we did that with the national survey, i believe the cluster surveys got extended.

**Comment by trietmnj** [comment]
Well, adding in more elements can be done as an extension in the manage-all prompt without impacting too much down stream dependencies. I think the more dependency-laden issue is whether to start off the survey as "inactive" until the elements are added. That's one way avoid the bug completely. The active status of the survey allows access to map page via the choose-active prompt.

If we fix the bug in the survey assignment (which is not trivial), how do we treat those "active" surveys without any element? Would they be consider completed since there are no element that can be assign? Which doesn't really make sense. Internally the completed variable is used in the assignment algorithm, so that introduces another dependency related problem.

**Comment by trietmnj** [comment]
The survey tray in the map page is what kicks off the assignment algorithm, so having the no elements active survey accessible via the choose-active prompt allows access to this ambiguity.

**Comment by HenryGeorgist** [comment]
so if a user completes the final survey - they would have the ambiguity (as well as any other logged in user participating in the same survey) but they would not be given the option for that survey once they log out and log back in

**Comment by HenryGeorgist** [comment]
if the api to fetch a survey returns an error, you could just say "no more elements to assign at this time" in the survey tray?

**Comment by trietmnj** [comment]
Yea that makes sense, I think I was conflating between assignment and survey, both are conceptually different in this framework. The completed status only applies to assignments and not surveys.

**Comment by trietmnj** [comment]
But if there are no elements anyway, then should they be active? A survey being active allows access to the map page via the choose-active prompt, which automatically pulls up the tray, which will say "no more elements to assign at this time." They won't have any real utility on the map page anyway.

**Comment by HenryGeorgist** [comment]
no i dont think it should be active - it should set to inactive if no elements exist.

that requires a feature to be able to add elements to an inactive survey by extending the manage surveys view

**Comment by trietmnj** [comment]
Ok yea, that seems like an elegant design
